version: 2

sources:
  - name: raw
    database: DEV
    schema: RAW
    tables:
      - name: user_session_channel
        identifier: USER_SESSION_CHANNEL
      - name: session_timestamp
        identifier: SESSION_TIMESTAMP

models:
  - name: session_summary
    description: "Analytics model for session data"
    columns:
      - name: sessionId
        description: "Unique identifier for each session"
        tests:
          - unique
          - not_null

  - name: raw
    database: dev
    schema: raw
    description: "Schema which stores raw tables (ETL)"
    tables:
      - name: stock_price_data
        identifier: stock_price_data
        description: "Stock price data has columns symbol, price_date, close"
  - name: analytics
    database: dev
    schema: analytics
    description: "Schema which stores analytics tables (ELT)"
    tables:
      - name: moving_average
        identifier: moving_average
        description: "Calculates SMA and EMA for stocks"      
      - name: rsi
        identifier: rsi
        description: "Calculates RSI for stocks"
      - name: price_momentum
        identifier: price_momentum
        description: "Calculates Price Momentum"
 